### ISSUE TITLE
Add Wordpress plugin

### ISSUE THREAD

**Issue by Jim-Anderson** [JBHemloque/SINBot#11]
Souvarine has requested this. The plugin should poll a wordpress blog and post a summary or short header of new articles in a given channel.

**Comment by Jim-Anderson** [comment]
Souvarine is unable to install the wp-json plugin, so the route we'll try going is to use the default WP rss feed.

The feed is at any of the following:
https://coloniagazette.wordpress.com/?feed=rss
https://coloniagazette.wordpress.com/?feed=rss2
https://coloniagazette.wordpress.com/?feed=rdf
https://coloniagazette.wordpress.com/?feed=atom

There's a package called feedparser that can handle rss: https://github.com/danmactough/node-feedparser

**Comment by JBHemloque** [comment]
Fixed with an RSS polling routine.
