### ISSUE TITLE
Some aliases in the FGEBot are no longer working.

### ISSUE THREAD

**Issue by Jim-Anderson** [JBHemloque/SINBot#6]
Do "show jaques"

**Result:** 
FGEBot - Today at 12:28 PM
Sorry, I have no information on undefined

**Expected:** A map showing the location of Jaques Station

Why is this happening? Fix this.

**Comment by Jim-Anderson** [comment]
Actually, they never were. Sysaliases are supported on some commands (the ones handled by edsmbot.js) support sysaliases, the others do not. They all should.

**Comment by JBHemloque** [comment]
Fixed in 0.11.0
